#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

# source node functions
source ${_CIOP_APPLICATION_PATH}/node/lib/functions.sh

export target=${TMPDIR}/input
mkdir -p ${target}

# Loops over all the inputs
while read inputfile 
do
  # report activity in log
  ciop-log "INFO" "The input file is: ${inputfile}"

  # stage-in the data
  get_data ${inputfile} ${target} || exit $?
done

# invoke the main function
main || exit $?

exit 0
